# language: swift
# xcode_project: StockServer.xcodeproj
# xcode_scheme: Run
# xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro Max
# osx_image: xcode11.3


os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode11.3
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
script:
  - swift build
  - swift build -c release