language: swift
os: osx
osx_image: xcode11.3
before script:
  - gem install xcpretty
script:
  - swift package generate-xcodeproj
  - set -o pipefail && xcodebuild -scheme StockServer-Package clean build test | xcpretty
