language: swift
os: osx
osx_image: xcode11.3
#services:
#  - postgresql
#addons:
#  postgresql: '12.2'
install:
  - sudo apt-get install -yq --no-install-suggests --no-install-recommends postgresql-common
  - sudo service postgresql stop
  - sudo apt install -yq --no-install-suggests --no-install-recommends postgresql-11 postgresql-client-11
  - sudo service postgresql start 11
  - sudo -u postgres psql -c 'create database stockserver_test;'
before_script:
  - gem install xcpretty
#  - psql -c 'create database stockserver_test;' -U postgres
script:
  - brew reinstall openssl@1.1
  - swift package generate-xcodeproj
  - set -o pipefail && xcodebuild -scheme Run -enableCodeCoverage YES clean build test | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)
